### ISSUE TITLE
Handle the case where Reeve Hoban and all of his units die before any of them are sighted

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Two_Brothers_With_A_Third_Difficulty#3]
This has actually happened to me before! When testing on HARD, to be specific. This would affect many of the other events in scenario 4.

**Comment by cooljeanius** [comment]
@knyghtmare also suggested giving Reeve Hoban the AI Controller once you discover him, too, so I'm going to track that here, as well.

Edit: does it even work and make sense to enable it during an event? Anyways, since the AI Controller is deprecated, if I do want to add it here, I should copy over the file with the macro for it into this campaign as I did for SotBEEE in cooljeanius/Son_Of_The_Black_Eye_Easy_Edition@ccf4813

**Comment by cooljeanius** [comment]
commit a54246e is a step towards starting work on this, but there's a still a long ways to go; I still need to decide what exactly I want to happen in this case... would it make sense to do dialogue with him being invisible? Ending the scenario in defeat might feel kind of unfair, but it would also negate all of the "well, then what do we do with these other events?" concerns, so I dunno, maybe that's still an option?

**Comment by cooljeanius** [comment]
@brirush84, since you were offering to help polish the writing for issue #4, and I'd want to add some additional dialogue for this issue, do you want to chime in here, as well?

**Comment by brirush84** [comment]
I can think of a couple options; one is to just make enemies never target him personally until you see him. The player will have no idea what's happening in the shroud, so it won't look odd unless they're cheating.

Since you already have a condition present in case he's dead, I think it might be good to 'resurrect him' with 1 hit point at the keep, give his message, and then die. The message could be slightly changed and I could work on that if you go this route.

**Comment by cooljeanius** [comment]
> I can think of a couple options; one is to just make enemies never target him personally until you see him. The player will have no idea what's happening in the shroud, so it won't look odd unless they're cheating.

Well, the enemy AI already has an `[avoid]` tag set up for the tiles around Reeve's keep, but the issue is that sometimes he leaves his keep to move onto a tile that they DON'T avoid... I guess I could try tweaking that?

> Since you already have a condition present in case he's dead, I think it might be good to 'resurrect him' with 1 hit point at the keep, give his message, and then die. The message could be slightly changed and I could work on that if you go this route.

Hm, I guess I'll just do the healing for now with commit f46a0d0 and think about the message later...

**Comment by cooljeanius** [comment]
> Hm, I guess I'll just do the healing for now with commit [f46a0d0](https://github.com/cooljeanius/Two_Brothers_With_A_Third_Difficulty/commit/f46a0d059bf3ed3eb2a2264befe6a15354c747f2) and think about the message later...

I want to get this part into my final 1.14 release, at least, even if the rest has to wait until post-1.16...

**Comment by cooljeanius** [comment]
> > Hm, I guess I'll just do the healing for now with commit [f46a0d0](https://github.com/cooljeanius/Two_Brothers_With_A_Third_Difficulty/commit/f46a0d059bf3ed3eb2a2264befe6a15354c747f2) and think about the message later...
> 
> I want to get this part into my final 1.14 release, at least, even if the rest has to wait until post-1.16...

ok I got it into [1.0.3](https://github.com/cooljeanius/Two_Brothers_With_A_Third_Difficulty/releases/tag/1.0.3); I guess I'll close this for now...
