### ISSUE TITLE
Give Arvith traits

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/Two_Brothers_With_A_Third_Difficulty#7]
See @Ashmyr's wesnoth/wesnoth#7129 
(possibly also give some to Reeve Hoban, too? Along with any other characters who might need some...)

**Comment by Ashmyr** [comment]
Resilient, Strong?

**Comment by Ashmyr** [comment]
Quick would get him killed fast due to lower HP and his need to attack enemies. I don't like Intelligent as it's not really useful here.

**Comment by cooljeanius** [comment]
> Resilient, Strong?

OK, given in 71c491b. N.B. that I haven't actually done an entire playthru with these traits yet; I've only tested loading the first scenario to make sure they're applied.
